import { NextRequest, NextResponse } from 'next/server';
import { prisma } from '@/lib/prisma';
import { getUserFromRequest } from '@/lib/auth';
import { DaemonClient } from '@/lib/services/daemon-client';

const CONFIG_PATH = 'config/voicechat/voicechat-server.properties';

// The handful of settings players/admins care about most. Everything else in the file
// (Simple Voice Chat writes ~20 keys) is preserved untouched via KNOWN_KEYS passthrough
// below rather than modeled here, since the exact key set varies across mod versions.
const KNOWN_KEYS = ['port', 'max_voice_distance', 'voice_chat_prefix', 'groups_enabled', 'group_radius', 'voice_host'];

const DEFAULTS: Record<string, string> = {
  port: '-1',
  max_voice_distance: '48.0',
  voice_chat_prefix: '/vc',
  groups_enabled: 'true',
  group_radius: '8.0',
  voice_host: '',
};

function parseProperties(text: string): { settings: Record<string, string>; lines: string[] } {
  const lines = text.split(/\r?\n/);
  const settings: Record<string, string> = {};
  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const idx = trimmed.indexOf('=');
    if (idx === -1) continue;
    settings[trimmed.slice(0, idx).trim()] = trimmed.slice(idx + 1).trim();
  }
  return { settings, lines };
}

// Merges new values into the existing file text in place, preserving comments, unknown
// keys, and line order — only appending keys that didn't already exist.
function mergeProperties(existingLines: string[], updates: Record<string, string>): string {
  const remaining = { ...updates };
  const out = existingLines.map((line) => {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) return line;
    const idx = trimmed.indexOf('=');
    if (idx === -1) return line;
    const key = trimmed.slice(0, idx).trim();
    if (key in remaining) {
      const value = remaining[key];
      delete remaining[key];
      return `${key}=${value}`;
    }
    return line;
  });

  for (const [key, value] of Object.entries(remaining)) {
    out.push(`${key}=${value}`);
  }

  return out.join('\n');
}

async function getDaemonClient(serverId: string) {
  const server = await prisma.server.findUnique({ where: { id: serverId }, include: { node: true } });
  if (!server) return null;
  const daemonClient = new DaemonClient({ host: server.node.host, port: server.node.port, apiKey: server.node.apiKey });
  // Matches the pattern used by files/read, files/write and mods/list — the daemon's
  // on-disk server directory is keyed by the plain DB id, not the container id.
  return { daemonClient, targetContainerId: server.id };
}

export async function GET(request: NextRequest, { params }: { params: { id: string } }) {
  const user = await getUserFromRequest(request);
  if (!user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });

  try {
    const ctx = await getDaemonClient(params.id);
    if (!ctx) return NextResponse.json({ error: 'Server not found' }, { status: 404 });

    try {
      const file = await ctx.daemonClient.readFile(ctx.targetContainerId, CONFIG_PATH);
      const { settings } = parseProperties(file.content);
      return NextResponse.json({ exists: true, knownKeys: KNOWN_KEYS, settings: { ...DEFAULTS, ...settings } });
    } catch (err: any) {
      // Config is generated by the mod on first boot — not existing yet is expected, not an error.
      return NextResponse.json({ exists: false, knownKeys: KNOWN_KEYS, settings: DEFAULTS });
    }
  } catch (err: any) {
    return NextResponse.json({ error: err.message || 'Failed to fetch Voice Chat configuration' }, { status: 500 });
  }
}

export async function POST(request: NextRequest, { params }: { params: { id: string } }) {
  const user = await getUserFromRequest(request);
  if (!user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });

  try {
    const ctx = await getDaemonClient(params.id);
    if (!ctx) return NextResponse.json({ error: 'Server not found' }, { status: 404 });

    const { settings } = await request.json();
    if (!settings || typeof settings !== 'object') {
      return NextResponse.json({ error: 'Missing settings object' }, { status: 400 });
    }

    let existingLines: string[] = [];
    try {
      const file = await ctx.daemonClient.readFile(ctx.targetContainerId, CONFIG_PATH);
      existingLines = file.content.split(/\r?\n/);
    } catch (err: any) {
      // First-ever write: start from the defaults, so we don't clobber keys we don't know about yet.
      existingLines = Object.entries(DEFAULTS).map(([k, v]) => `${k}=${v}`);
    }

    const merged = mergeProperties(existingLines, settings);
    await ctx.daemonClient.writeFile(ctx.targetContainerId, CONFIG_PATH, merged);

    return NextResponse.json({ success: true, message: 'Voice Chat configuration saved — changes take effect on the next server restart.' });
  } catch (err: any) {
    return NextResponse.json({ error: err.message || 'Failed to save Voice Chat configuration' }, { status: 500 });
  }
}
