import fs from 'fs';
import path from 'path';
import { execSync } from 'child_process';

/**
 * Working out what a pre-built server directory actually is.
 *
 * Used when the files arrive already assembled — a migration, or a pack uploaded whole —
 * so nothing chose the loader and the directory has to be read for it.
 *
 * This used to be two lines, duplicated, that looked for `user_args.txt`/`unix_args.txt`
 * and otherwise said Fabric. Those two files are generated by the Forge installer from
 * 1.17 onwards and by nothing before it, so every Forge pack older than that — which is
 * most large ones, SkyFactory 4 and the whole 1.12.2 era included — was labelled Fabric.
 * The container then downloaded a current Fabric server into a directory of 1.12.2 Forge
 * mods and died on the first tick, with a panel header reading FABRIC LATEST above a
 * folder plainly full of Forge.
 *
 * So: positive evidence for each loader, in order of how specific the evidence is, and an
 * honest null when there is none. A caller that gets null should keep whatever the panel
 * already believes rather than guessing.
 */

export type DetectedLoader = 'FABRIC' | 'QUILT' | 'NEOFORGE' | 'FORGE';

export interface TypeDetection {
  loader: DetectedLoader | null;
  /** Minecraft version read off a jar name, when one was there to read. */
  version: string | null;
  /** The file that decided it, for the log — this guess is worth being able to audit. */
  evidence: string | null;
}

function exists(dir: string, name: string): boolean {
  try {
    return fs.existsSync(path.join(dir, name));
  } catch {
    return false;
  }
}

function listing(dir: string): string[] {
  try {
    return fs.readdirSync(dir);
  } catch {
    return [];
  }
}

/**
 * The Minecraft version out of a loader jar's filename.
 *
 * `forge-1.12.2-14.23.5.2860-installer.jar` carries both the Minecraft version and the
 * Forge build; the first is the one itzg needs, and taking the wrong one asks for a
 * Minecraft that does not exist.
 */
export function versionFromJarName(name: string): string | null {
  const match = /^(?:forge|neoforge|fabric|quilt)-(\d+\.\d+(?:\.\d+)?)-/i.exec(name);
  return match ? match[1] : null;
}

export function detectServerType(serverDir: string): TypeDetection {
  const files = listing(serverDir);
  const has = (name: string) => exists(serverDir, name);

  // --- Fabric and Quilt: unambiguous launcher artefacts, so they go first ---
  for (const marker of ['fabric-server-launch.jar', 'fabric-server-launcher.jar', 'fabric-server-launcher.properties']) {
    if (has(marker)) return { loader: 'FABRIC', version: null, evidence: marker };
  }
  if (has('quilt-server-launch.jar')) {
    return { loader: 'QUILT', version: null, evidence: 'quilt-server-launch.jar' };
  }

  // --- NeoForge before Forge: it ships the same args files, and "forge" is a substring
  // of "neoforge", so testing Forge first would swallow every NeoForge pack ---
  if (exists(serverDir, path.join('libraries', 'net', 'neoforged'))) {
    return { loader: 'NEOFORGE', version: null, evidence: 'libraries/net/neoforged' };
  }
  const neoJar = files.find((f) => /^neoforge-.*\.jar$/i.test(f));
  if (neoJar) return { loader: 'NEOFORGE', version: versionFromJarName(neoJar), evidence: neoJar };

  // --- Forge 1.17+ ---
  for (const marker of ['user_args.txt', 'unix_args.txt']) {
    if (has(marker)) return { loader: 'FORGE', version: null, evidence: marker };
  }
  if (exists(serverDir, path.join('libraries', 'net', 'minecraftforge'))) {
    return { loader: 'FORGE', version: null, evidence: 'libraries/net/minecraftforge' };
  }

  // --- Forge 1.16 and older: a universal or installer jar, with the version in its name ---
  const forgeJar = files.find((f) => /^forge-.*\.jar$/i.test(f));
  if (forgeJar) return { loader: 'FORGE', version: versionFromJarName(forgeJar), evidence: forgeJar };

  /*
   * The FTB-style launcher scripts, which is how packs of that era were distributed:
   * ServerStart plus settings, with the Forge installer run on first boot. Weaker
   * evidence than a jar, so it is last — but on a pack that has never been started it is
   * the only evidence there is.
   */
  if ((has('ServerStart.sh') || has('ServerStart.bat')) && (has('settings.sh') || has('settings.bat'))) {
    return { loader: 'FORGE', version: null, evidence: 'ServerStart/settings launcher scripts' };
  }

  return { loader: null, version: null, evidence: null };
}


/**
 * Jar names that are never the server, however alone they are in the directory.
 *
 * An installer is the trap this exists for. Forge and NeoForge ship one, it is often the
 * only jar a server pack contains before first boot, and running it with no arguments
 * opens a Swing wizard — which in a container with no display and no fonts dies inside
 * FontManagerFactory with an InternalError that never mentions Forge at all.
 */
export const NON_SERVER_JAR = /(installer|sources|javadoc|serverpackcreator|-slim|-extra|-client)\.?[^/]*\.jar$/i;

/** The jars in a directory that could plausibly be run as a server, best first. */
export function serverJarCandidates(dir: string, exclude: string[] = []): string[] {
  const skip = new Set(exclude.map((n) => n.toLowerCase()));
  try {
    return fs
      .readdirSync(dir)
      .filter((f: string) => f.toLowerCase().endsWith('.jar'))
      .filter((f: string) => !skip.has(f.toLowerCase()))
      .filter((f: string) => !NON_SERVER_JAR.test(f))
      // A universal or server jar is the real thing; anything else is a guess.
      .sort((a: string, b: string) => Number(/universal|server/i.test(b)) - Number(/universal|server/i.test(a)));
  } catch {
    return [];
  }
}

/** The Forge or NeoForge installer sitting in a directory, if there is one. */
export function findForgeInstaller(dir: string): string | null {
  try {
    return fs.readdirSync(dir).find((f: string) => /^(neo)?forge-.*installer.*\.jar$/i.test(f)) ?? null;
  } catch {
    return null;
  }
}

/**
 * Turns a Forge/NeoForge installer into an actual server, the way it is meant to be used.
 *
 * `--installServer` is what makes it headless: without it the jar assumes a desktop and
 * opens its wizard. Forcing java.awt.headless too means a future installer that still
 * reaches for the toolkit fails with something legible rather than a font stack trace.
 *
 * Failure is not fatal. The caller falls back to whatever else it can find, so a pack that
 * cannot be installed reports through the ordinary "no server jar" path.
 */
export function runForgeInstaller(dir: string, installerJar: string): boolean {
  console.log(`[Forge] ${installerJar} is an installer, not a server. Running it with --installServer...`);
  try {
    execSync(`java -Djava.awt.headless=true -jar "${installerJar}" --installServer`, {
      cwd: dir,
      // Forge downloads its whole library tree here; on a cold cache that is minutes.
      timeout: 10 * 60 * 1000,
      maxBuffer: 32 * 1024 * 1024,
      stdio: 'pipe',
    });
    console.log(`[Forge] Installer finished. Directory now: ${fs.readdirSync(dir).join(', ')}`);
    return true;
  } catch (e: any) {
    console.warn(`[Forge] Installer failed: ${e?.stderr?.toString?.() || e.message}`);
    return false;
  }
}
