import fs from 'fs';
import path from 'path';
import { execSync } from 'child_process';

/**
 * Working out what a pre-built server directory actually is.
 *
 * Used when the files arrive already assembled — a migration, or a pack uploaded whole —
 * so nothing chose the loader and the directory has to be read for it.
 *
 * This used to be two lines, duplicated, that looked for `user_args.txt`/`unix_args.txt`
 * and otherwise said Fabric. Those two files are generated by the Forge installer from
 * 1.17 onwards and by nothing before it, so every Forge pack older than that — which is
 * most large ones, SkyFactory 4 and the whole 1.12.2 era included — was labelled Fabric.
 * The container then downloaded a current Fabric server into a directory of 1.12.2 Forge
 * mods and died on the first tick, with a panel header reading FABRIC LATEST above a
 * folder plainly full of Forge.
 *
 * So: positive evidence for each loader, in order of how specific the evidence is, and an
 * honest null when there is none. A caller that gets null should keep whatever the panel
 * already believes rather than guessing.
 */

export type DetectedLoader = 'FABRIC' | 'QUILT' | 'NEOFORGE' | 'FORGE';

export interface TypeDetection {
  loader: DetectedLoader | null;
  /** Minecraft version read off a jar name, when one was there to read. */
  version: string | null;
  /** The file that decided it, for the log — this guess is worth being able to audit. */
  evidence: string | null;
}

function exists(dir: string, name: string): boolean {
  try {
    return fs.existsSync(path.join(dir, name));
  } catch {
    return false;
  }
}

function listing(dir: string): string[] {
  try {
    return fs.readdirSync(dir);
  } catch {
    return [];
  }
}

/**
 * The Minecraft version out of a loader jar's filename.
 *
 * `forge-1.12.2-14.23.5.2860-installer.jar` carries both the Minecraft version and the
 * Forge build; the first is the one itzg needs, and taking the wrong one asks for a
 * Minecraft that does not exist.
 */
export function versionFromJarName(name: string): string | null {
  const match = /^(?:forge|neoforge|fabric|quilt)-(\d+\.\d+(?:\.\d+)?)-/i.exec(name);
  return match ? match[1] : null;
}

export function detectServerType(serverDir: string): TypeDetection {
  const files = listing(serverDir);
  const has = (name: string) => exists(serverDir, name);

  // --- Fabric and Quilt: unambiguous launcher artefacts, so they go first ---
  for (const marker of ['fabric-server-launch.jar', 'fabric-server-launcher.jar', 'fabric-server-launcher.properties']) {
    if (has(marker)) return { loader: 'FABRIC', version: null, evidence: marker };
  }
  if (has('quilt-server-launch.jar')) {
    return { loader: 'QUILT', version: null, evidence: 'quilt-server-launch.jar' };
  }

  // --- NeoForge before Forge: it ships the same args files, and "forge" is a substring
  // of "neoforge", so testing Forge first would swallow every NeoForge pack ---
  if (exists(serverDir, path.join('libraries', 'net', 'neoforged'))) {
    return { loader: 'NEOFORGE', version: null, evidence: 'libraries/net/neoforged' };
  }
  const neoJar = files.find((f) => /^neoforge-.*\.jar$/i.test(f));
  if (neoJar) return { loader: 'NEOFORGE', version: versionFromJarName(neoJar), evidence: neoJar };

  // --- Forge 1.17+ ---
  for (const marker of ['user_args.txt', 'unix_args.txt']) {
    if (has(marker)) return { loader: 'FORGE', version: null, evidence: marker };
  }
  if (exists(serverDir, path.join('libraries', 'net', 'minecraftforge'))) {
    return { loader: 'FORGE', version: null, evidence: 'libraries/net/minecraftforge' };
  }

  // --- Forge 1.16 and older: a universal or installer jar, with the version in its name ---
  const forgeJar = files.find((f) => /^forge-.*\.jar$/i.test(f));
  if (forgeJar) return { loader: 'FORGE', version: versionFromJarName(forgeJar), evidence: forgeJar };

  /*
   * The FTB-style launcher scripts, which is how packs of that era were distributed:
   * ServerStart plus settings, with the Forge installer run on first boot. Weaker
   * evidence than a jar, so it is last — but on a pack that has never been started it is
   * the only evidence there is.
   */
  if ((has('ServerStart.sh') || has('ServerStart.bat')) && (has('settings.sh') || has('settings.bat'))) {
    return { loader: 'FORGE', version: null, evidence: 'ServerStart/settings launcher scripts' };
  }

  return { loader: null, version: null, evidence: null };
}


/**
 * Jar names that are never the server, however alone they are in the directory.
 *
 * An installer is the trap this exists for. Forge and NeoForge ship one, it is often the
 * only jar a server pack contains before first boot, and running it with no arguments
 * opens a Swing wizard — which in a container with no display and no fonts dies inside
 * FontManagerFactory with an InternalError that never mentions Forge at all.
 */
export const NON_SERVER_JAR = /(installer|sources|javadoc|serverpackcreator|-slim|-extra|-client)\.?[^/]*\.jar$/i;

/**
 * How good a candidate a jar is, highest first.
 *
 * The ranking matters more than it looks. A Forge install leaves `minecraft_server.1.12.2.jar`
 * in the directory — Forge needs vanilla's jar alongside its own — and that file is a
 * dependency, never the thing to launch. Ranking it top, which a plain /server/ match does,
 * starts a plain vanilla server: it boots, says "Starting minecraft server version 1.12.2",
 * loads no mods, and generates an ordinary world. Indistinguishable from the loader being
 * wrong, and reached by a completely different route.
 */
function jarRank(name: string): number {
  // Vanilla's jar sitting beside a loader's. Last resort, and only when nothing else is
  // here at all — for a genuinely vanilla directory it is still the right answer.
  if (/^minecraft_server[._-]/i.test(name)) return 0;
  // A loader's own launch jar, named for the loader that produced it.
  if (/^(forge|neoforge|fabric|quilt)[-_]/i.test(name)) return /universal/i.test(name) ? 3 : 2;
  return 1;
}

/**
 * The jars in a directory that could plausibly be run as a server, best first.
 *
 * `serverType` matters. Without it this is loader-blind, and a directory holding both a
 * Forge build and a leftover Fabric launcher happily offers the Fabric one to a Forge
 * server — the same substitution, arrived at through the fallback instead of through the
 * named checks. Each candidate is asked what it is before it is offered.
 */
export function serverJarCandidates(dir: string, exclude: string[] = [], serverType?: string): string[] {
  const skip = new Set(exclude.map((n) => n.toLowerCase()));
  try {
    return fs
      .readdirSync(dir)
      .filter((f: string) => f.toLowerCase().endsWith('.jar'))
      .filter((f: string) => !skip.has(f.toLowerCase()))
      .filter((f: string) => !NON_SERVER_JAR.test(f))
      .filter((f: string) => jarSuitsLoader(path.join(dir, f), serverType))
      .sort((a: string, b: string) => jarRank(b) - jarRank(a));
  } catch {
    return [];
  }
}

/** The Forge or NeoForge installer sitting in a directory, if there is one. */
export function findForgeInstaller(dir: string): string | null {
  try {
    return fs.readdirSync(dir).find((f: string) => /^(neo)?forge-.*installer.*\.jar$/i.test(f)) ?? null;
  } catch {
    return null;
  }
}

/**
 * Turns a Forge/NeoForge installer into an actual server, the way it is meant to be used.
 *
 * `--installServer` is what makes it headless: without it the jar assumes a desktop and
 * opens its wizard. Forcing java.awt.headless too means a future installer that still
 * reaches for the toolkit fails with something legible rather than a font stack trace.
 *
 * Failure is not fatal. The caller falls back to whatever else it can find, so a pack that
 * cannot be installed reports through the ordinary "no server jar" path.
 */
export function runForgeInstaller(dir: string, installerJar: string): boolean {
  console.log(`[Forge] ${installerJar} is an installer, not a server. Running it with --installServer...`);
  try {
    execSync(`java -Djava.awt.headless=true -jar "${installerJar}" --installServer`, {
      cwd: dir,
      // Forge downloads its whole library tree here; on a cold cache that is minutes.
      timeout: 10 * 60 * 1000,
      maxBuffer: 32 * 1024 * 1024,
      stdio: 'pipe',
    });
    console.log(`[Forge] Installer finished. Directory now: ${fs.readdirSync(dir).join(', ')}`);
    return true;
  } catch (e: any) {
    console.warn(`[Forge] Installer failed: ${e?.stderr?.toString?.() || e.message}`);
    return false;
  }
}


/**
 * Whether a directory's contents contradict the loader the panel thinks it has.
 *
 * The failure this catches is the quiet one. A Forge modpack started as a Fabric server
 * does not crash — Fabric boots, finds no Fabric mods, ignores the Forge ones entirely,
 * and generates an ordinary Minecraft world. The panel says running, the port answers,
 * players join, and the pack is simply not there. Nothing in a log says why, because from
 * the server's point of view nothing went wrong.
 *
 * So a mismatch is worth refusing to start for. A server that will not boot sends someone
 * looking; a vanilla world pretending to be SkyFactory does not.
 *
 * Deliberately narrow. It fires only when the directory holds a populated mods folder —
 * i.e. this really is a modpack, not a bare server someone will add mods to later — and
 * only when the evidence names a different loader. No evidence means no opinion.
 */
export function loaderMismatch(serverDir: string, serverType?: string): string | null {
  const configured = (serverType || '').toUpperCase();
  if (!['FABRIC', 'FORGE', 'NEOFORGE', 'QUILT'].includes(configured)) return null;

  let modCount = 0;
  try {
    modCount = fs.readdirSync(path.join(serverDir, 'mods')).filter((f) => f.toLowerCase().endsWith('.jar')).length;
  } catch {
    return null;
  }
  if (modCount === 0) return null;

  const detected = detectServerType(serverDir);
  if (!detected.loader || detected.loader === configured) return null;

  return (
    `This server is set to ${configured}, but its files are ${detected.loader}` +
    `${detected.version ? ` ${detected.version}` : ''} — found ${detected.evidence}, alongside ` +
    `${modCount} mods. Starting it as ${configured} would load none of them and generate an ordinary ` +
    `Minecraft world. Set this server to ${detected.loader}` +
    `${detected.version ? ` ${detected.version}` : ''} in the panel (Update Centre), then start it again.`
  );
}

/**
 * What a jar actually is, read from its own manifest.
 *
 * Filenames lie and metadata rots. A Fabric server download is saved as `server.jar`, so a
 * directory that once ran Fabric keeps a `server.jar` that is a Fabric launcher — and the
 * launcher check "if server.jar exists, use it" happily started it for a Forge server. The
 * name carried no information, and craftcontrol-meta.json had already been overwritten to
 * claim Forge, so neither source could tell the truth.
 *
 * The manifest can. Main-Class names the loader that built the jar, and nothing rewrites it.
 */
export function jarLoader(jarPath: string): DetectedLoader | 'VANILLA' | null {
  let mainClass = '';
  try {
    // Lazily required so this module stays importable where adm-zip is not needed.
    const AdmZip = require('adm-zip');
    const entry = new AdmZip(jarPath).getEntry('META-INF/MANIFEST.MF');
    if (!entry) return null;
    const manifest = entry.getData().toString('utf8');
    // Manifest lines wrap at 72 bytes with a leading space on continuations.
    const unwrapped = manifest.replace(/\r?\n /g, '');
    mainClass = /Main-Class:\s*(\S+)/.exec(unwrapped)?.[1] || '';
  } catch {
    // Unreadable, not a zip, or missing. No opinion — the caller keeps its previous belief.
    return null;
  }

  if (!mainClass) return null;
  if (/fabric/i.test(mainClass)) return 'FABRIC';
  if (/quilt/i.test(mainClass)) return 'QUILT';
  if (/neoforge/i.test(mainClass)) return 'NEOFORGE';
  if (/(minecraftforge|forge)/i.test(mainClass)) return 'FORGE';
  if (/net\.minecraft\./i.test(mainClass)) return 'VANILLA';
  return null;
}

/**
 * Whether an existing server.jar can be reused for the loader now configured.
 *
 * Only refuses on positive evidence of a different loader. An unreadable jar, or one whose
 * manifest names nothing recognisable, is left alone: re-downloading a server because a
 * manifest could not be parsed would be a worse failure than the one being prevented.
 */
export function jarSuitsLoader(jarPath: string, serverType?: string): boolean {
  const configured = (serverType || '').toUpperCase();
  if (!LOADER_TYPES.includes(configured)) return true;

  const actual = jarLoader(jarPath);
  if (actual === null) return true;

  // A Forge server legitimately keeps vanilla's jar around as a dependency, but it is
  // never what server.jar should be for one.
  return actual === configured;
}

const LOADER_TYPES = ['FABRIC', 'FORGE', 'NEOFORGE', 'QUILT'];
